export const AUTH_ACTIONS = Symbol('AuthActions')
export const AUTH_RESOURCE = Symbol('AuthResource')

export const CREATE_DTO = Symbol('CreateDto')
export const CREATE_RESPONSE = Symbol('CreateResponse')
export const FIND_BY_ID_RESPONSE = Symbol('FindByIdResponse')
export const FIND_MANY_FILTER = Symbol('FindManyFilter')
export const FIND_MANY_RESPONSE = Symbol('FindManyResponse')
export const UPDATE_DTO = Symbol('UpdateDto')
export const UPDATE_ONE_RESPONSE = Symbol('UpdateOneResponse')
export const UPDATE_MANY_FILTER = Symbol('UpdateManyFilter')
export const UPDATE_MANY_RESPONSE = Symbol('UpdateManyResponse')
export const DELETE_BY_ID_RESPONSE = Symbol('DeleteByIdResponse')
export const DELETE_MANY_RESPONSE = Symbol('DeleteManyResponse')
export const FIND_MANY_SELECT_ENUM = Symbol('FindManySelectEnum')